### ISSUE TITLE
Hzn-cli not found on clean sdo onboarding.[Issue]

### ISSUE THREAD

**Issue by peeksake** [open-horizon/SDO-support#49]
**Issue**

**Details**
After running simulate-mfg.script on device to be onboarded and passing voucher to horizon admin that imports it to exchange, no CLI is installed to the sdo agent. 

**Expected Behavior** 
HZN packages if not found are installed via owner boot device script.

**Actual Behavior**

```/usr/sdo/bin/owner-boot-device ibm.helloworld```

reaches this stage 

```28-09-2020 09:18:46.715 INFO  [main] org.sdo.cri.device.DeviceApp.lambda$applicationRunner$1 - device onboarding ends
/usr/sdo/bin/owner-boot-device: line 63: hzn: command not found
Waiting for agreement for ibm.helloworld /usr/sdo/bin/owner-boot-device: line 63: hzn: command not found
./usr/sdo/bin/owner-boot-device: line 63: hzn: command not found```

**Comment by peeksake** [comment]
verified on a clean vm by @lorenzoking.

@bmpotter I assumed here that those packages would not be included in the initial onboarding, so not in ```simulate-mfg.sh```, and would be put on to the device via leveraging the onboarding boot up? did I make a correct assumption about the model?

**Comment by lorenzoking** [comment]
Solution: Previously, neither `simulate-mfg.sh` or `owner-boot-device` checked to see if the command jq was install nor did it install it if it wasn't. I added a function and modified some code in `simulate-mfg.sh` to check for jq and install if its not there. That alone fixes the whole situation so that it does install hzn packages if not found via owner boot device script.

**Comment by peeksake** [comment]
this was resolved
